services:
    twigdate.listener.request:
        class: Bini\Bundle\WebBundle\Services\TwigDateRequestListener
        arguments: [@twig]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }